# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe1f4c0eb44534a319c94c33f2054328740d0226094cbe998bab0bb1a7cbdb454304f7a68a61a0ef3ab6a7bed588ed0ab30edb9cbd231eda33c6c0aacf8d19e

test:
  secret_key_base: e576af161fbf0df253dcab5dee36172ad44f5474cedc2eed47ca51a588da713d8d02929e11544850b8b9f2f5d8547262648035538c1bf1ab84dbee7b38538500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
